import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { Header } from "./dashboard/_components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "GURUJI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
      <Header/>
      {children}
      <Toaster />
      </body>
    </html>
    </ClerkProvider>
  );
}
